# Generated by Django 4.2.7 on 2026-03-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contentpage_metatag_reviewreport_trendingsearch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('store_update', 'Store Update'), ('offer', 'Offer'), ('lead', 'New Lead'), ('message', 'Message'), ('payment', 'Payment'), ('review', 'Review'), ('system', 'System'), ('promotion', 'Promotion')], max_length=50),
        ),
    ]
