# Generated by Django 4.2.7 on 2026-02-27 17:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0007_amenity_area_city_pincode_reviewreaction_state_and_more'),
        ('vendor_panel', '0002_subscriptionplan_vendorsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(db_index=True, max_length=15)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_city', models.CharField(blank=True, max_length=100)),
                ('product_interest', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('qualified', 'Qualified'), ('converted', 'Converted'), ('rejected', 'Rejected')], default='new', max_length=20)),
                ('source', models.CharField(choices=[('direct', 'Direct Contact'), ('search', 'Search'), ('featured', 'Featured Listing'), ('advertisement', 'Advertisement'), ('referral', 'Referral'), ('other', 'Other')], default='direct', max_length=20)),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('last_contacted_at', models.DateTimeField(blank=True, null=True)),
                ('quality_score', models.PositiveSmallIntegerField(default=0, help_text='0-100')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='stores.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_credits', models.PositiveIntegerField(default=0)),
                ('total_used', models.PositiveIntegerField(default=0)),
                ('total_purchased', models.PositiveIntegerField(default=0)),
                ('last_purchase', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lead_credits', to='stores.store')),
            ],
            options={
                'verbose_name_plural': 'Lead Credits',
            },
        ),
        migrations.CreateModel(
            name='LeadCreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('transaction_type', models.CharField(choices=[('add', 'Added'), ('use', 'Used'), ('refund', 'Refunded')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='vendor_panel.leadcredit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('credits', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percentage', models.PositiveSmallIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('razorpay', 'Razorpay'), ('stripe', 'Stripe'), ('upi', 'UPI'), ('netbanking', 'Netbanking'), ('card', 'Card'), ('wallet', 'Wallet')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('purpose', models.CharField(choices=[('subscription', 'Subscription'), ('featured_listing', 'Featured Listing'), ('lead_credits', 'Lead Credits'), ('advertisement', 'Advertisement'), ('other', 'Other')], max_length=20)),
                ('transaction_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('order_id', models.CharField(blank=True, max_length=255)),
                ('signature', models.CharField(blank=True, max_length=500)),
                ('gateway_response', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='stores.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='requested', max_length=20)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_refunds', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund', to='vendor_panel.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreClickLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_type', models.CharField(choices=[('call', 'Call'), ('whatsapp', 'WhatsApp'), ('direction', 'Direction'), ('website', 'Website'), ('review', 'Review'), ('message', 'Message'), ('email', 'Email'), ('share', 'Share'), ('favorite', 'Add to Favorites')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_type', models.CharField(default='web', max_length=20)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_logs', to='stores.store')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('device_type', models.CharField(default='web', max_length=20)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='stores.store')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending', 'Pending Payment')], default='pending', max_length=20)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('renewed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('auto_renewal', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='kycdocument',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['display_order'], 'verbose_name_plural': 'Subscription Plans'},
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='document_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='document_type',
            field=models.CharField(choices=[('aadhar', 'Aadhar'), ('pan', 'PAN'), ('gst', 'GST Certificate'), ('udyog', 'Udyog Aadhar'), ('llp', 'LLP Agreement'), ('company', 'Company Registration'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='verification_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='analytics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='api_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='billing_cycle',
            field=models.PositiveIntegerField(default=30, help_text='Days'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='custom_domain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='featured_duration_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='featured_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Number of featured listings allowed'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='highlight_color',
            field=models.CharField(blank=True, default='#328BC9', max_length=7),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_recurring',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='leads_per_month',
            field=models.PositiveIntegerField(default=0, help_text='0 for unlimited'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_gallery_images',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_images',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_products',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_services',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium'), ('featured', 'Featured'), ('enterprise', 'Enterprise')], default='free', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='priority_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='verified_badge',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='kycdocument',
            unique_together={('user', 'document_type')},
        ),
        migrations.DeleteModel(
            name='VendorSubscription',
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_panel.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='stores.store'),
        ),
        migrations.AddField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendor_panel.subscription'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadcredittransaction',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendor_panel.payment'),
        ),
        migrations.AddIndex(
            model_name='storeviewlog',
            index=models.Index(fields=['store', '-viewed_at'], name='vendor_pane_store_i_c11637_idx'),
        ),
        migrations.AddIndex(
            model_name='storeviewlog',
            index=models.Index(fields=['-viewed_at'], name='vendor_pane_viewed__bbc07a_idx'),
        ),
        migrations.AddIndex(
            model_name='storeclicklog',
            index=models.Index(fields=['store', 'click_type'], name='vendor_pane_store_i_f4c135_idx'),
        ),
        migrations.AddIndex(
            model_name='storeclicklog',
            index=models.Index(fields=['store', '-clicked_at'], name='vendor_pane_store_i_e8d335_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['store', 'status'], name='vendor_pane_store_i_b7f2d8_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'status'], name='vendor_pane_user_id_8332b5_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['-created_at'], name='vendor_pane_created_6c7c5f_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['store', 'status'], name='vendor_pane_store_i_7e4b84_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['store', '-created_at'], name='vendor_pane_store_i_c74953_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['customer_phone'], name='vendor_pane_custome_03b9fb_idx'),
        ),
    ]
