# Generated by Django 4.2.7 on 2026-03-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_panel', '0003_lead_leadcredit_leadcredittransaction_leadpackage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycdocument',
            name='document_type',
            field=models.CharField(choices=[('aadhar', 'Aadhar'), ('pan', 'PAN'), ('gst', 'GST Certificate'), ('udyog', 'Udyog Aadhar'), ('llp', 'LLP Agreement'), ('company', 'Company Registration'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium'), ('featured', 'Featured'), ('enterprise', 'Enterprise')], max_length=20, unique=True),
        ),
    ]
