# Generated by Django 4.2.7 on 2026-03-08 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_loginlog_userotpverification_alter_user_options_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='loginlog',
            new_name='account_log_user_id_6650ac_idx',
            old_name='accounts_lo_user_id_63346c_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='account_use_user_ty_77fcc4_idx',
            old_name='accounts_us_user_ty_029544_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='account_use_email_553b8f_idx',
            old_name='accounts_us_email_74c8d6_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='account_use_phone_664a69_idx',
            old_name='accounts_us_phone_f54457_idx',
        ),
        migrations.AlterModelTable(
            name='loginlog',
            table='account_login_log',
        ),
        migrations.AlterModelTable(
            name='user',
            table='account_user',
        ),
        migrations.AlterModelTable(
            name='userotpverification',
            table='account_user_otp_verification',
        ),
    ]
