# Generated by Django 4.2.7 on 2026-03-08 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='service',
            table='service_service',
        ),
        migrations.AlterModelTable(
            name='servicecategory',
            table='service_category',
        ),
    ]
