# Generated by Django 4.2.7 on 2026-03-23 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_table_alter_servicecategory_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name_plural': 'Service'},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'verbose_name_plural': 'Service category'},
        ),
    ]
