# Generated by Django 6.0.2 on 2026-02-27 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_wishlistitem'),
        ('stores', '0005_storeitemcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='store_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.storeitemcategory'),
        ),
    ]
