# Generated by Django 4.2.7 on 2026-03-08 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_store_category'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product_product',
        ),
        migrations.AlterModelTable(
            name='productcategory',
            table='product_category',
        ),
        migrations.AlterModelTable(
            name='productreview',
            table='product_review',
        ),
        migrations.AlterModelTable(
            name='wishlistitem',
            table='product_wishlist_item',
        ),
    ]
