# Generated by Django 4.2.7 on 2026-03-23 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_table_alter_productcategory_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Product'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'Product category'},
        ),
        migrations.AlterModelOptions(
            name='productreview',
            options={'verbose_name_plural': 'Product review'},
        ),
        migrations.AlterModelOptions(
            name='wishlistitem',
            options={'verbose_name_plural': 'Wishlist item'},
        ),
    ]
