# Generated by Django 6.0.2 on 2026-02-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_categoryrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='theme_color',
            field=models.CharField(default='#324bc9', max_length=7),
        ),
        migrations.AddField(
            model_name='store',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
