# Generated by Django 6.0.2 on 2026-02-27 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_favoritestore'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_categories', to='stores.store')),
            ],
            options={
                'unique_together': {('store', 'slug')},
            },
        ),
    ]
