# Generated by Django 4.2.7 on 2026-03-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_amenity_area_city_pincode_reviewreaction_state_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='store',
            new_name='store_store_categor_f07c38_idx',
            old_name='stores_stor_categor_07ebf9_idx',
        ),
        migrations.RenameIndex(
            model_name='store',
            new_name='store_store_rating_0001a6_idx',
            old_name='stores_stor_rating_6240cf_idx',
        ),
        migrations.RenameIndex(
            model_name='storereview',
            new_name='store_revie_store_i_0ed721_idx',
            old_name='stores_stor_store_i_ce5b58_idx',
        ),
        migrations.RenameIndex(
            model_name='storereview',
            new_name='store_revie_created_805ccb_idx',
            old_name='stores_stor_created_00bfec_idx',
        ),
        migrations.RenameIndex(
            model_name='storevisit',
            new_name='store_visit_store_i_392703_idx',
            old_name='stores_stor_store_i_6bc5e8_idx',
        ),
        migrations.AlterField(
            model_name='storecategory',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['area', 'is_active'], name='store_store_area_id_45b926_idx'),
        ),
        migrations.AlterModelTable(
            name='amenity',
            table='store_amenity',
        ),
        migrations.AlterModelTable(
            name='area',
            table='store_area',
        ),
        migrations.AlterModelTable(
            name='categoryrequest',
            table='store_category_request',
        ),
        migrations.AlterModelTable(
            name='city',
            table='store_city',
        ),
        migrations.AlterModelTable(
            name='favoritestore',
            table='store_favorite_store',
        ),
        migrations.AlterModelTable(
            name='pincode',
            table='store_pincode',
        ),
        migrations.AlterModelTable(
            name='reviewreaction',
            table='store_review_reaction',
        ),
        migrations.AlterModelTable(
            name='state',
            table='store_state',
        ),
        migrations.AlterModelTable(
            name='store',
            table='store_store',
        ),
        migrations.AlterModelTable(
            name='storecategory',
            table='store_category',
        ),
        migrations.AlterModelTable(
            name='storegallery',
            table='store_gallery',
        ),
        migrations.AlterModelTable(
            name='storeitemcategory',
            table='store_item_category',
        ),
        migrations.AlterModelTable(
            name='storeoffer',
            table='store_offer',
        ),
        migrations.AlterModelTable(
            name='storereview',
            table='store_review',
        ),
        migrations.AlterModelTable(
            name='storevisit',
            table='store_visit',
        ),
    ]
