# Generated by Django 4.2.7 on 2026-03-23 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_rename_stores_stor_categor_07ebf9_idx_store_store_categor_f07c38_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name_plural': 'Amenity'},
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['name'], 'verbose_name_plural': 'Area'},
        ),
        migrations.AlterModelOptions(
            name='categoryrequest',
            options={'verbose_name_plural': 'Category request'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name_plural': 'City'},
        ),
        migrations.AlterModelOptions(
            name='favoritestore',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Favorite store'},
        ),
        migrations.AlterModelOptions(
            name='pincode',
            options={'ordering': ['code'], 'verbose_name_plural': 'Pincode'},
        ),
        migrations.AlterModelOptions(
            name='reviewreaction',
            options={'verbose_name_plural': 'Review reaction'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['name'], 'verbose_name_plural': 'State'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['-featured', '-rating', '-created_at'], 'verbose_name_plural': 'Store'},
        ),
        migrations.AlterModelOptions(
            name='storecategory',
            options={'ordering': ['display_order', 'name'], 'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='storegallery',
            options={'ordering': ['display_order', 'created_at'], 'verbose_name_plural': 'Gallery image'},
        ),
        migrations.AlterModelOptions(
            name='storeitemcategory',
            options={'ordering': ['display_order', 'name'], 'verbose_name_plural': 'Item category'},
        ),
        migrations.AlterModelOptions(
            name='storeoffer',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Offer'},
        ),
        migrations.AlterModelOptions(
            name='storereview',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Review'},
        ),
        migrations.AlterModelOptions(
            name='storevisit',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Visit'},
        ),
    ]
