# Generated by Django 4.2.7 on 2026-04-13 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0009_alter_amenity_options_alter_area_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryrequest',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
